name: CATs-PlusPlus
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.8.2=py3.8_cuda11.1_cudnn8.0.5_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.8.2=py38
  - torchvision=0.9.2=py38_cu111
  - typing_extensions=4.3.0=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - albumentations==1.3.0
    - charset-normalizer==2.1.1
    - einops==0.5.0
    - filelock==3.8.0
    - huggingface-hub==0.10.1
    - idna==3.4
    - imageio==2.22.2
    - joblib==1.2.0
    - networkx==2.8.7
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.5.0
    - protobuf==3.20.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.28.1
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.2
    - tensorboardx==2.5.1
    - termcolor==2.0.1
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==0.6.11
    - tqdm==4.64.1
    - urllib3==1.26.12
